language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
script: composer test
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - Build/Travis/bin
    - Build/Travis/Build
    - Build/Travis/Configuration
    - Build/Travis/Data
    - Build/Travis/Packages
    - Build/Travis/Web