language: php
php:
  - '7.2'
script: composer test
cache:
  directories:
    - Build/Travis/bin
    - Build/Travis/Build
    - Build/Travis/Configuration
    - Build/Travis/Data
    - Build/Travis/Packages
    - Build/Travis/Web