PackageFactory:
  AtomicFusion:
    PropTypes:
      enable: false

Neos:
  Fusion:
    defaultContext:
      PropTypes: \PackageFactory\AtomicFusion\PropTypes\Eel\PropTypesHelper
  Neos:
    fusion:
      autoInclude:
        'PackageFactory.AtomicFusion.PropTypes': true
